In [1]:
#Ek NumPy array banao jisme 1 se 10 tak numbers ho

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#Ek 2D array banao (3x3) random integers ke saath.

import numpy as np
arr=np.random.randint(1,23,size=(3,3))
print(arr)


arrr=np.random.randint(1,12,size=(5,5))
print(arrr)

[[ 5 10 18]
 [ 6  5 18]
 [ 1 21 18]]
[[ 3  1  3  5  6]
 [ 5  5 11  7 11]
 [ 9 10  2  1  4]
 [10 10  4  8  5]
 [ 1  1  9 10  5]]


In [6]:
#Array ka shape, size, aur datatype print karo.
import numpy as np
var=np.random.randint(1,12,size=(5,5))
print("data type ",var.dtype)
print("shape",var.shape)
print("size",var.size)

data type  int32
shape (5, 5)
size 25


In [12]:
#1D array ka max, min, mean, sum nikalna.

import numpy as np

arr=np.array([1,2,3,4])
print("minimam size",np.min(arr))
print("maximam size",np.max(arr))
print("Average size",np.mean(arr))
print("sum of array",np.sum(arr))

minimam size 1
maximam size 4
Average size 2.5
sum of array 10


In [17]:
#Array ko reshape karke (2x5) bana do.
#2*5==10 ok to ham ko 1d array me 10 lena padhe ga 
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10])
reshaPe=arr.reshape(2,5)
print(reshaPe)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#Ek array ko reverse karo.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1]) # ye indexing se hota hai 
print(np.flip(arr))# ye funtion use karke bhi hota hai 


#Indexing & Slicing

In [27]:
#Ek array ka 3rd se 7th element print karo.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3:7])   # [start:end:step:]

[4 5 6 7]


In [32]:
#2D array me se sirf second column lo
arrr=np.random.randint(1,12,size=(2,6))
print(arrr)
print()
print("the second column")
print(arrr[:,1])


[[ 7  6 11  6  5  5]
 [ 8  6  5  8  3  5]]

the second column
[6 6]


In [34]:
#3x3 identity matrix banao.

import numpy as np

identitymatrics= np.identity(3)
print(identitymatrics)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#Ek array ke sirf even numbers print karo.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even=arr[arr%2==0]
print(even)

[ 2  4  6  8 10]


In [39]:
#Ek array ke elements ko slice karke dusre array me copy karo.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2=arr[4:-1].copy() #es se aray ki alag copy bana gi
print(arr)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10]
[5 6 7 8 9]


#Mathematical Operations

In [40]:
#1D array ke har element ko 2 se multiply karo.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr*2)

[ 2  4  6  8 10 12 14 16 18 20]


In [44]:
#1D array ke har element ka square root nikalna.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [46]:
#Dono arrays ka element-wise sum aur dot product.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1+arr2)
print(np.dot(arr1,arr2))

[5 7 9]
32


In [49]:
#Sin, Cos aur Tan values ka array banao.
import numpy as np
arr1 = np.array([1, 2, 3])
print(np.sin(arr1))
print(np.cos(arr1))
print(np.tan(arr1))


[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


In [51]:
#Broadcasting ka use karke har row me +10 add karo. 
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result=arr+10
print("Original Array:\n", arr)
print("\nAfter Broadcasting (+10):\n", result)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After Broadcasting (+10):
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


Random, Unique & Sorting

In [53]:
#Random integers ka array banao (size = 15, 1 to 100 range).
arr=np.random.randint(1,100,size=15)
print(arr)

[29 47 46 88 72 22  4 70 23 62  7 57  6 73 94]


In [55]:
#Array ke unique values aur unki count nikalna
arr=np.array([1,1,1,2,3,4,4,4,4,5,6,6,6,7,7,7,8,8,8,8,8])
unique_array,count=np.unique(arr,return_count=True)
print("Unique Values:", unique_values)
print("Counts:", counts)


TypeError: unique() got an unexpected keyword argument 'return_count'

In [1]:
#Array ko reshape karke (2x5) bana do.
import numpy as np

arr=np.array([1,2,3,4])
print(arr)

reshaPe=arr.reshape(2,5)
print(reshaPr)

[1 2 3 4]


ValueError: cannot reshape array of size 4 into shape (2,5)

In [3]:
#Array ke unique values aur unki count nikalna.
import numpy as np

arr = np.array([1,1,1,1,2,2,2,2, 2,3,3,3, 3, 4, 4, 4, 5, 6, 6, 7])

unique_values, counts = np.unique(arr, return_counts=True)

print("Unique Values:", unique_values)
print("Counts:", counts)


Unique Values: [1 2 3 4 5 6 7]
Counts: [4 5 4 3 1 2 1]


In [8]:
#Array ko ascending aur descending sort karo.
import numpy as np

arr = np.array([4, 5, 4, 3, 1, 2, 1])


print("ascending",np.sort(arr))


print(" Descending",np.sort(arr)[::-1])


ascending [1 1 2 3 4 4 5]
 Descending [5 4 4 3 2 1 1]


In [13]:
#Random array ka median aur standard deviation nikalna.
import numpy as np

arr = np.random.randint(1, 100, size=10)
print(arr)

print("standard deviation ::",np.std(arr))
print("median deviation ::",np.median(arr))

[ 4 84 27 61 54 15 39 45 61 47]
standard deviation :: 22.454620905283615
median deviation :: 46.0


#Logical & Filtering

In [18]:
#Ek array me se sirf 50 se bade numbers filter karo
import numpy as np
arr=np.array([81,62,43,44,54])
arr2=arr[arr>=50]
print(arr2)

[81 62 54]


In [21]:
#Boolean mask ka use karke values replace karo (e.g., jo 30 se chhote hain unko 0 bana do).
arr = np.array([10, 25, 33, 45, 5, 60])
mask = arr < 30

arr[mask] = 0 # replace  kare ga30 se chhota hua t0

[33 45 60]


In [23]:
#NumPy ka where() use karke even ko "E" aur odd ko "O" me convert karo.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
resu=np.where(arr%2==0,"E","O")
print(resu)


['O' 'E' 'O' 'E' 'O' 'E']
